version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # ボリュームマウントは必要に応じて設定
      - ./web/lib:/app/lib
      - ./web/pubspec.yaml:/app/pubspec.yaml

  api:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./api:/app
